### ISSUE TITLE
channel.setfounder doesn't store info to db

### ISSUE THREAD

**Issue by abma** [spring/uberserver#123]
each lobby server restart info is gone:
https://github.com/spring/uberserver/blob/master/protocol/Channel.py#L119

https://github.com/spring/uberserver/blob/master/ChanServ.py#L99
(see chanserv code, too)

**Comment by abma** [comment]
seems to be the most annoying bug currently because of "regular" restarts

**Comment by silentwings** [comment]
topic owner was also forgotten, fixed in above commit
all channel operators are also forgotten (haven't fixed that)

**Comment by silentwings** [comment]
note: channel operators are also forgotten
