### ISSUE TITLE
Vision Eightfold

### ISSUE THREAD

**Issue by Anarchid** [spring/uberserver#141]
Since today, attempting to send messages to #moddev via Springlobby or SWL results in the message being echoed back eight (or more) times, and not being delivered to other participants in the channel:

```
15:38:27 spreng_llll brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
15:38:27 brijt deslavt
```

Messages sent via IRC Bridge are not repeated, but are not delivered to channel participants from other lobbies either. Private messages work normally.

Other lobbies likely affected, but not tested.

**Comment by PicassoCT** [comment]
Can reproduce

**Comment by abma** [comment]
oO
thanks, will investigate soon

**Comment by Anarchid** [comment]
I'm faster.

**Comment by abma** [comment]
doh! thanks!

**Comment by abma** [comment]
if det is available, he can update like this:

su lobby
cd /home/lobby/uberserver
git pull

and then as admin send "reload" command

(i can do in ~2 hours or so)

**Comment by abma** [comment]
...done!
