### ISSUE TITLE
LISTSUBSCRIPTIONS seem broken

### ISSUE THREAD

**Issue by cleanrock** [spring/uberserver#149]
If this command is supposed to list channels i am subscribed to its broken.
After successfully subscribed to sy i got 237 LISTSUBSCRIPTION messages as response, probably all channels.
If b345f90 is deployed i suspect it did not do what was intended.

**Comment by abma** [comment]
nope, b345f903ee5dd382a4d7c41d0ed82c8497d2676b isn't deployed yet

**Comment by abma** [comment]
i've deployed the changes...
