### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by gajop** [spring/uberserver#151]
Unit that test the Spring lobby interface should be implemented.
TestLobbyClient should be forked, and written to use the python unittest library: https://docs.python.org/2/library/unittest.html 
One abstract class should be created that sets up the server connection but doesn't do much else. It should still implement the interface (out_ commands). 
Writing tests would include inheriting it and calling the various out_ methods while handling the in_ methods.

Thoughts?

**Comment by abma** [comment]
what do you want to test with these unit tests?

if lobby servers "response" to commands are valid?

or if internal state is updated probably after a command is received?

or both?

**Comment by gajop** [comment]
I think I'd just test the command responses, by subjecting uberserver to both valid and invalid commands and see how it responds.
I'm already technically doing it by copying/pasting commands in the debug console of my lua client, but I just think it would be much better to create something automated which can be also used for regression testing.
Testing the internal state seems harder to write, but also not really as important imo (it can be inferred). The commands it sends is what matters.

**Comment by abma** [comment]
agreed. makes few sense to check internal state as on most changes tests have to be adjusted and only the data which is send to clients matters.

some "tests" already exists for the db backend: https://github.com/spring/uberserver/blob/master/SQLUsers.py#L1014

> One abstract class should be created that sets up the server connection but doesn't do much else.

does that mean a tcp connection or will you just create an extra client.Send() method? (this is maybe the simpler approach)

**Comment by gajop** [comment]
I think client.Send is usable for anything we might need

**Comment by silentwings** [comment]
i think this is done in as much as is practical

also CLEANUP tests the internal state (and it was complicated to write...)
