### ISSUE TITLE
channel subscription do not get all messages on join

### ISSUE THREAD

**Issue by cleanrock** [spring/uberserver#154]
I have been subscribed to #sy on both uberserver and zk server the last week and it looks like uberserver misses a lot of messages.
When i connected to uberserver today i got ~20 messages and 100+ from Nightwatch when i connected to zk server.
uberserver gave me the oldest messages, my guess is uberserver did not send me the messages posted after midnight (the ones written today).

**Comment by abma** [comment]
can you be more specific?

**Comment by abma** [comment]
in other words: are you sure that nightwatch isn't broken and forwards messages? there are very few messages from nightwatch in #sy.

**Comment by cleanrock** [comment]
I think you should test this, keep one client connected and see if your client that connects next day gets all you see in the always connected client.
I will see if i see something bad in uberserver code later today.

**Comment by gajop** [comment]
I can confirm that indeed messages are lost.
Example: (uber) http://pastebin.com/CtBNvwR0s , (ZK) http://pastebin.com/ffMKAu57

**Comment by abma** [comment]
uh, weird. i guess sql query is wrong than as some users are completely missing in these pastes:

abma_irc & [PRO]Jools

need to investigate further

**Comment by cleanrock** [comment]
When i joined now the messages from uber was pretty equal to zk, zk sends messages in wrong order though so its a bit tricky to compare but just looking at the lines and comparing some they looked pretty equal.
Side note: uber sent a few messages (~15) from when i was already connected yesterday but i think that is only a good feature.

**Comment by cleanrock** [comment]
When i joined now uber missed a lot, all ~50 lines from last 12 hours.

**Comment by abma** [comment]
this line very likely contains the error:
https://github.com/spring/uberserver/blob/master/SQLUsers.py#L875

**Comment by abma** [comment]
see #156 
(basicly should be fixed, but needs full server restart as db connect param changed)
