### ISSUE TITLE
LISTSUBSCRIPTIONS is not documented in lobby protocol api

### ISSUE THREAD

**Issue by LinLo** [spring/uberserver#160]
Hi, i have "*\* Server *\* LISTSUBSCRIPTIONS failed. Command does not exist." on springlobby.
LISTSUBSCRIPTIONS is not described in https://github.com/spring/LobbyProtocol.
Is it a LobbyProtocol miss or uberserver bug ?
Thank you.

**Comment by abma** [comment]
no, thats some different bug, not sure how this error can happen, i guess lobby server requires a full restart.

its missing in lobby protocol => TODO

**Comment by abma** [comment]
LISTSUBSCRIPTIONS is deprecated: #183
