### ISSUE TITLE
MYBATTLESTATUS, battleStatus 0 should be ok

### ISSUE THREAD

**Issue by cleanrock** [spring/uberserver#170]
I get this error message now:
SERVERMSG MYBATTLESTATUS failed - invalid status is below 1: 0. Please update your lobby!

Looking at http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#MYBATTLESTATUS:client 0 is an ok value.

**Comment by abma** [comment]
http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#CLIENTSTATUS:server

"Sent by the server to all registered clients, indicating that a client's status changed. Note that client's status is considered 0 if not indicated otherwise (for example, when you login, the server sends only statuses of those clients whose statuses differ from 0, to save bandwidth). "

i guess that should apply to the client command, too?

**Comment by abma** [comment]
in other words: why do you want to send 0? what status should it indicate?

**Comment by cleanrock** [comment]
Not sure what you mean there about client status.

I send it because i know very little at this point (and 0 is ok according to spec), e.g. UPDATEBATTLEINFO is sent after REQUESTBATTLESTATUS:

D-15:51:43-ServerConn.cpp:109] ServerConn::send JOINBATTLE 185 _ scriptPassword1043217850
D-15:51:43-Model.cpp:239] message: JOINBATTLE 185 -2567621
D-15:51:43-Model.cpp:1472] modHash 4292399675
D-15:51:43-Model.cpp:1473] mapHash 3294430168
D-15:51:43-Model.cpp:239] message: SETSCRIPTTAGS < snip >
D-15:51:43-Model.cpp:239] message: JOINEDBATTLE 185 cleanrock scriptPassword1043217850
D-15:51:43-Model.cpp:239] message: CLIENTBATTLESTATUS BlackHoleHost1 4194306 16777215
D-15:51:43-Model.cpp:239] message: CLIENTBATTLESTATUS [DoR]Dartagnan 4194396 16711935
< snip, more CLIENTBATTLESTATUS messages>
D-15:51:43-Model.cpp:239] message: ADDSTARTRECT 0 0 0 60 200
D-15:51:43-Model.cpp:239] message: ADDSTARTRECT 1 140 0 200 200
D-15:51:43-Model.cpp:239] message: REQUESTBATTLESTATUS
D-15:51:43-ServerConn.cpp:109] ServerConn::send MYBATTLESTATUS 0 255
D-15:51:43-Model.cpp:239] message: SERVERMSG MYBATTLESTATUS failed - invalid status is below 1: 0. Please update your lobby!
D-15:51:43-Model.cpp:239] message: UPDATEBATTLEINFO 185 7 0 -1000537128 SapphireShores_Duo_V2.1
D-15:51:43-ServerConn.cpp:109] ServerConn::send MYBATTLESTATUS 8388608 255
D-15:51:43-Model.cpp:239] message: CLIENTBATTLESTATUS cleanrock 0 255

**Comment by abma** [comment]
ok, will fix, thanks for reporting!

**Comment by abma** [comment]
fyi: will take a bit until applied. due to some other changes can't directly apply this change.

also the message is (atm) informal only, so shouldn't break anything...
