### ISSUE TITLE
xmlrpc interface crashes

### ISSUE THREAD

**Issue by dansan** [spring/uberserver#172]
Currently users cannot login to the replay site.

```python
>>> from xmlrpclib import ServerProxy
>>> client = ServerProxy('https://springrts.com/api/uber/xmlrpc')
>>> client.get_account_info("username", "s3cr3t")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'NoneType' object has no attribute 'clientFromUsername'">
```

**Comment by abma** [comment]
reverted to the last known working commit:

531d29f05640f1ae57d491515653bece37feea2a

:-(

(so everything fine now, but current development branch is heavily broken it seems)

**Comment by dansan** [comment]
I get
`ProtocolError for springrts.com/api/uber/xmlrpc: 403 Forbidden`
now.

**Comment by abma** [comment]
from which ip are you trying? only replays.springrts.com is allowed atm... and i can login there?!

**Comment by dansan** [comment]
Yes, from replays.springrts.com. You can login with the `abma` or `springfiles` SSH accounts. The django installation is at `/var/www/servers/replays.springrts.com/spring-replay-site/`, the virtualenv you'll have to load if you want to run something in the django shell is at `/var/www/servers/replays-test.springrts.com/virtenv/`.

Oh hey -  it works now - thank you!!  :-)
