### ISSUE TITLE
OnUserJoinedBattle() Spam

### ISSUE THREAD

**Issue by FLOZi** [spring/uberserver#173]
OnUserJoinedBattle(): Lobby server inconsistency: user in battle which doesn't exit. Please report as lobby server bug!

I get this as a popup message starting SpringLobby and can't close it or remove it -> SL is now useless.

**Comment by LOeT-Zinn** [comment]
**+1**

see: https://github.com/springlobby/springlobby/issues/442#issuecomment-102666471

**Comment by abma** [comment]
reverted to the last known working commit:

531d29f05640f1ae57d491515653bece37feea2a

:-(

(so everything fine now, but current development branch is heavily broken it seems)

**Comment by abma** [comment]
not fixed but duplicate of #173

thanks for reporting!
