### ISSUE TITLE
russian channel topic

### ISSUE THREAD

**Issue by jamerlan** [spring/uberserver#180]
I set a topic in "ru" channel a few days ago. It was working good. But now it is broken
[00:28:24] ** Channel topic:
[00:28:24] Invalid unicode-encoding (should be utf-8)
[00:28:24] ** Set by [teh]decay
how to do it properly? I did that: !topic Добро пожаловать в русскоязычное сообщество Spring RTS! http://vk.com/taspring Если возникли вопросы, можете задать в группе или здесь (отвечают не моментально! надо подождать)

when you just execute command !topic it looks like everything was OK but if you re-connect - you see "Invalid unicode-encoding (should be utf-8)" instead of the topic.

I tried to use: springlobby, weblobby -  the same behaviour

**Comment by abma** [comment]
https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L1518

very likely ".decode(UNICODE_ENCODING)" isn't needed here
