### ISSUE TITLE
improve channel history / remove channel subscription

### ISSUE THREAD

**Issue by abma** [spring/uberserver#183]
-> let the lobby client sent what history it wants:
- lobby server doesn't need to store a date
- no gaps when client crashed / timed out

ideally by last msg id and not by time

**Comment by gajop** [comment]
-> let the lobby client sent what history it wants:
+1, and ideally also allow the lobby to retrieve historical data that has already been sent (keep history).
This is pretty useful when switching PCs/lobbies without having to rely on local backups.

**Comment by abma** [comment]
todo:

1. implement client side
2. remove the old implementation (especially the check in SQLUsers.py / get_channel_history for subscription)
3. remove subscription table / commands

**Comment by silentwings** [comment]
rel #312 #241

**Comment by abma** [comment]
just an idea:

modify DataHandler.broadcast and change msg to be a dict, i.e. for BATTLEOPENED

class Command:
       params = []
       def __init__(**args)
       def JsonFormat(self)
       ...
       def TextFormat(self):.
      ...

class CommandParam:
     def __init__(name, value, is_sentence=False)


cmd = Command(
CommandParam("battle_id", battle.battle_id)
CommandParam("type", battle.type)
CommandParam("natType", battle.natType)
CommandParam("username", host.username)
CommandParam("ip", battle.ip)
CommandParam("port", battle.port)
CommandParam("maxplayers", battle.maxplayers)
CommandParam("passworded", battle.passworded())
CommandParam("rank", battle.rank,)
CommandParam("maphash", battle.maphash)
CommandParam("engine", battle.engine)
CommandParam("version", battle.version)
CommandParam("map", battle.map, True)
CommandParam("title", battle.title, True)
CommandParam("modname", battle.modname, True)
CommandParam("name", battle.name, True)
)


DataHandler.multicast:

...

jsonmsg = command.JsonFormat()
textmsg = command.TextFormat()

for session_id in session_ids:
...
if client.supports_json:
    client.Send(jsonmsg)
else:
    client.Send(textmsg)


does this sound meaningful? this way the formating of msgs is done in a single place and not spread over the whole Protocol.py.

**Comment by silentwings** [comment]
I understand what you mean but this seems relevant to https://github.com/spring/uberserver/issues/249 rather than here?

For the text version, the order of the params needs to be recorded.

**Comment by silentwings** [comment]
as far as i can see, all this has already been done
