### ISSUE TITLE
allow only clients with matchmaking support to join hosts with matchmaking support

### ISSUE THREAD

**Issue by abma** [spring/uberserver#189]
so forcejoin doesn't fail

**Comment by gajop** [comment]
I assume you meant to say "clients *without* matchmaking support"?

**Comment by abma** [comment]
yes! (to many no's)

**Comment by gajop** [comment]
;)
btw, it's *too* many :p

**Comment by abma** [comment]
sh.... thanks! :-)

**Comment by silentwings** [comment]
I guess this can be closed, after https://github.com/spring/uberserver/commit/7e14fd1ced8a411c0a8f6d0eb9cc2b3739e9167b

**Comment by abma** [comment]
nice catch!

fixed by removal XD
