### ISSUE TITLE
remove custom encryption code

### ISSUE THREAD

**Issue by abma** [spring/uberserver#195]
unused / difficult to maintain / difficult to write clients

**Comment by gajop** [comment]
Despite the fact that Kloot must have spent considerable amount of time to contribute this, I am in favor of the change to remove it, simply because it's bound to be less secure and no one has time to implement this in their client.
+1

**Comment by abma** [comment]
https://github.com/spring/uberserver/commit/061c47d68c44023482bf5dc1ba51bf67a27ed16d

(+ some more commits)

**Comment by abma** [comment]
was/is replaced by STARTTLS, see #193
