### ISSUE TITLE
Bad string type check

### ISSUE THREAD

**Issue by sanguinariojoe** [spring/uberserver#200]
# Problem:

A bad type checking is causing this kind of assertion errors:

```
ERROR DataHandler.error:331  Error in handling data from client: , #1 PING
, Traceback (most recent call last):
  File "/home/pepe/Downloads/uberserver/twistedserver.py", line 37, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/pepe/Downloads/uberserver/Client.py", line 160, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), msg_limits)
  File "/home/pepe/Downloads/uberserver/Client.py", line 170, in HandleProtocolCommands
    assert(type(split_data[-1]) == str)
AssertionError
```

# Solution:

Replace all the string type checks of the form `type(var) == str` by `isinstance(var, basestring)`

# Explanation:

In general `isinstance` should be used instead of `type(var) == whatever`. Moreover, the strings type is one of the best examples of that:

```
>>> s = u''
>>> type(s) == str
False
>>> type(s) == unicode
True
>>> type(s) == basestring
False
```

As you can see, it becomes impossible to check the type of a string with a single comparison while `isinstance` is not applied:

```
>>> isinstance(s, basestring)
True
```

**Comment by abma** [comment]
are you using python3 or python2?

**Comment by sanguinariojoe** [comment]
Python2 (In Python3 the unicode type has been removed, as well as basestring). Along this line I suggest you to add the following at the begin of the scripts:

```
if (sys.version_info > (3, 0)):
    basestring = str
```

**Comment by abma** [comment]
python3 is enforced, this basicly is fixed.

**Comment by abma** [comment]
i'll give typing a try to replace the asserts.

https://docs.python.org/3/library/typing.html +
http://mypy-lang.org/
