### ISSUE TITLE
adjust TOS for gdpr

### ISSUE THREAD

**Issue by abma** [spring/uberserver#217]
https://springrts.com/phpbb/viewtopic.php?f=73&t=36288&p=582605#p582605

http://www.geekshed.net/tos/

sth. like:

"It is prohibited to share channel content of secret or private (channel modes +s and +p respectively) channels or those channels with ChanServ’s "Restricted Access" set over any medium without permission of the channel owner. These mediums include, but are not limited to, the web, other IRC networks and IM networks. Channel owners can reserve all rights to redefine the scope of this rule on a per channel basis."

**Comment by abma** [comment]
quakenet tos:
http://quakenet.org/help/103
freenode TOS:
https://freenode.net/policies

discord:
https://discordapp.com/terms

zero-k

???

**Comment by silentwings** [comment]
https://springrts.com/wiki/Terms_of_Service#Terms_of_Service_of_the_Lobby_Server

"You agree not to share, broadcast or relay the content of any private channels, secret channels, or channels with restricted access, without the explicit permission of the channel owner."
