### ISSUE TITLE
BANLIST gives accountIDs but not usernames

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#220]
The BANLIST command returns a list of all current bans, but it only supplies the accountIDs and doesn't supply the usernames (it used to give both, I think). Afaics lobby moderators have no way to convert accountIDs into usernames, so it is not possible for us to tell who is on the banlist.

**Comment by abma** [comment]
this change requires a server restart to be applied.

i want to investigate / fix #221 first before doing so
