### ISSUE TITLE
inconsistent data sent to clients

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#222]

**Comment by abma** [comment]
can you be more specific? the server didn't "crash". the process is still running.

what happened?

**Comment by abma** [comment]
thats whats suspicious at this time:
http://paste.springfiles.com/view/raw/a665299b

atm i don't see any relationship with the updated server: could be a network / vm issue. (i.e. network outage, server overloaded)

**Comment by abma** [comment]
i guess we had this again some minutes ago.

it looks like the lobby server makes spads crash / disconnect:

https://github.com/Yaribz/SPADS/issues/31

**Comment by abma** [comment]
-> 
CLIENTSTATUS" command before the "ACCEPTED" command. This doesn't make sense of course, the corresponding client ([ACE]Ticot) hasn't even been declared to SPADS yet. => inconsistency detected => broken connection

**Comment by abma** [comment]
oops:

telnet lobby.springrts.com 8200
Trying 78.46.100.157...
Connected to springrts.com.
Escape character is '^]'.
TASServer 0.36 103.0 8201 0
UPDATEBATTLEINFO 37 2 1 1380705307 DeltaSiege
UPDATEBATTLEINFO 45 1 0 1163709214 IsisDelta_v02
UPDATEBATTLEINFO 39 1 0 809342852 Battle for Planet XIV - v05
UPDATEBATTLEINFO 41 1 0 366473537 Frozen_Gauntlet_TNM03-V2
CLIENTSTATUS Petch 12
JOINEDBATTLE 13 [CAT]Fartass

:-)

**Comment by jamerlan** [comment]
Is this fix deployed? Becasue today we got this error.
Looks like some player did something wrong intentionally. 
I guess he spammed a draw commands or smth to crash the host. Host crashed - lobby got this error and disconnects.

**Comment by abma** [comment]
> Is this fix deployed? Becasue today we got this error.
yes.
> Looks like some player did something wrong intentionally.
> I guess he spammed a draw commands or smth to crash the host. Host crashed - lobby got this error and disconnects.

without details i can do nothing. spads.log is needed at least.
