### ISSUE TITLE
deleting users who didn't player for 30 days?

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#225]
I think https://github.com/spring/uberserver/commit/d4326a00e7b3006056505ae33e22eea5a201eb2c will cause a lot of grief, and could even lower BAs players numbers in the long run.

It's not uncommon for BA players to take a few weeks or months, or in some cases even years, away from playing BA, and then later return. I think they're much more likely to carry on doing this if their accounts don't vanish.

Possible remedy is that user accounts that have got significant ingame time (say, gold star or higher) wait longer (I'd say 2y is sensible) without a login before being deleted.

**Comment by abma** [comment]
i think you didn't understand or i miss-spelled:

only players who have no ingame time (!!!) are deleted

so a minute ingame time prevents the deletion of the account for 3 years.

imo thats ok, also its just a small adjustment to fit better.

**Comment by nicfreeman1209** [comment]
I misunderstood, apologies.

**Comment by abma** [comment]
no worries, its good when you ask / give feedback / complain. :)

**Comment by Yaribz** [comment]
FYI, several autohosts were using dedicated rank-0 lobby accounts to upload replays on the replay site (as indicated in [the README.replay-upload file](https://github.com/dansan/spring-replay-site/blob/master/README.replay-upload#L39)). So this change broke replay uploading for them, and currently a lot of replays are lost...

**Comment by abma** [comment]
autohosts usually have ingame time...

**Comment by Yaribz** [comment]
Please re-read my message

**Comment by abma** [comment]
he cleanup exists since years. so this change didn't introduce problems, it just made them appear faster.

**Comment by Yaribz** [comment]
exactly

**Comment by abma** [comment]
the problem is that a dedicated user just for uploading is used IMO.

**Comment by abma** [comment]
https://github.com/dansan/spring-replay-site/issues/108

**Comment by gajop** [comment]
How about you only delete accounts which didn't *login* in the last 30 days and have 0 ingame time?

**Comment by abma** [comment]
please read the code... thats exactly how it works currently.

logging in via replays.springrts.com doesn't update the last login, see the bug report at spring-replay-site. its argueable if this should be changed. ATM the api for logging in has only read-only permissions to the database of the lobbyserver.

IMHO its still favorable to use the same account for uploading and the autohost account. using different accounts is confusing and problems with the account very likely will be unnoticed.

**Comment by gajop** [comment]
good then, i went by the title and comments, which suggested otherwise.

I think there are accounts which aren't used to play/spectate games so this is something to keep in mind. Sending an email warning the users after some time would be a good policy. (The email field is optional iirc?)

**Comment by abma** [comment]
locked conversation: i'm really frustrated about invalid comments. i don't have the time for this.
