### ISSUE TITLE
plaintext auth

### ISSUE THREAD

**Issue by abma** [spring/uberserver#243]
needed for matrix auth provider:

needs tls + should be json encoded.

sth. like:

JSON {"LOGIN": {
"username": "abc", 
"password": "1234",
"clientid": 1234,
"client": "SpringLobby",
...
}}

**Comment by TurBoss** [comment]
not really needed because now we have our own auth provider :) 
it uses current xmlrpc

needs testing

**Comment by abma** [comment]
where is the git repo? :-)

**Comment by TurBoss** [comment]
creating it just now!

**Comment by TurBoss** [comment]
https://github.com/TurBoss/matrix-synapser-uberserver-xmlrpc

**Comment by abma** [comment]
awesome, thanks!

**Comment by TurBoss** [comment]
but works for you?
ehheehhe
