### ISSUE TITLE
 Trouble testing a self-ran Ubserver

### ISSUE THREAD

**Issue by tzaeru** [spring/uberserver#251]
Heya,

I forked uberserver and tried to test it a bit.

There's a few issues;
Firstly, the installation info is a little bit outdated/off for Ubuntu at least. Python2.7 is generally the system default, while Uberserver needs Python3.x. Could make a note of that in the README. Also, the library is not libssl-1.0-dev, but libssl-dev.

Now I got it running, but I can't seem to be able to register by using SpringLobby to connect to my server; SL simply closes the connection with "Connection to the other side was lost in a non-clean fashion: Connection lost.". I'm not sure if this is purely SpringLobby's fault or if I'm doing something wrong with Uber.

TestLobbyClient.py seems to be a bit outdated. UberServer uses '\n' as the pipe character, but TestLobby doesn't actually add it to any commands. I added '\n' after some commands and got it working a little wee bit, but when trying to register, I get "[REGISTRATIONDENIED][time=1518789901::iter=3] Invalid MD5-checksum.".

in_REGISTER() in protocol.py looks a bit messy. It's combining new and old style password checks, whatever those are supposed to be.

I'd like to add some stuff to the UberServer like (optional) email verification, but I just gotta first figure out how to get this to run properly with the aforementioned problems.

**Comment by abma** [comment]
the README mentions python 3:

https://github.com/spring/uberserver#requirements

are you using the latest version of uberserver?

whats the output of "git describe"?

for me TestLobbyClient.py works + in_REGISTER doesn't contain such code.

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L760

**Comment by abma** [comment]
and yes, the testlobbyclient was broken, this commit partly fixes it:

https://github.com/spring/uberserver/commit/12cf1605f1d130fc2e3c135c16be4d8d0596b640

**Comment by abma** [comment]
> Now I got it running, but I can't seem to be able to register by using SpringLobby to connect to my server; SL simply closes the connection with "Connection to the other side was lost in a non-clean fashion: Connection lost.". I'm not sure if this is purely SpringLobby's fault or if I'm doing something wrong with Uber.

can you look into ~/.springlobby/springlobby.log? could be encryption as a certificate should be automatically created.

**Comment by abma** [comment]
no feedback -> closing
