### ISSUE TITLE
Properly implement end-battle notify

### ISSUE THREAD

**Issue by specing** [spring/uberserver#252]
```
springlobby/src/gui/battlelist/battledataviewcttrl.cpp:
void BattleDataViewCtrl::OnNotifyGameEnd(wxCommandEvent& /*unused*/)
{
    const IBattle* battle = GetSelectedItem();

    if (battle == nullptr) {
        return;
    }

    //Send user (belived to be autohost bot) private message with "!notify" command
    User founder = battle->GetFounder();
    founder.Say("!notify");
}
```

This is bad.

**Comment by silentwings** [comment]
More detail needed, or perhaps you ate talking about something that is implemented by SPADS.

There is no end battle notify command in the lobby protocol.

**Comment by abma** [comment]
hm, this clearly is a feature request for the lobby client: the ingame status of the battlehost is send.

the !notify command really is not needed.
