### ISSUE TITLE
Why is 'SS' on the nasty words list?

### ISSUE THREAD

**Issue by SSNuTCrAcK** [spring/uberserver#253]
Greetings, first and foremost my respect and gratitude to anyone who is involved in developing this neat little game.

Apparently there is a 'nasty-word-list' which includes among other things the abbreviation 'SS'. I get the message each time i log in, which directed me here.

I don't want to argue about whether it is PC or not, to have 'SS' in your name, that would be silly. I question, why having PC rules at all, in this tiny corner of a corner of an outskirt of the internet. Why strain us with the burdens of restrictions of the political narrative, when we, at least in this remote, insignificant place, have the freedom to decide, whether to carry them or not.

A humble merchant of nuts 
NuTCrAcK aka Nusswaffen[SS]

**Comment by gajop** [comment]
I would've understood your complaint if you were suggesting that this word might prevent nicks such as assistant or it could be used as abbreviation for other things such as Super Saiyan.. but judging from your nick it definitely seems you want to use in connotation to Nazism, which is definitely not allowed here.
