### ISSUE TITLE
Host unable to connect to lobby server 

### ISSUE THREAD

**Issue by LordTeabag** [spring/uberserver#255]
> Postby abma » 15 Jan 2018, 11:59
automatic updates where installed and because of this the database server (mariadb) was restarted. the lobby server seems to fail to automatically reconnect to the db server -> some weird errors.

> Unread postby Silentwings » 17 Mar 2018, 21:36
For info: seems that this causes autohosts to be unable to reconnect to the lobbyserver, but I'm unsure of why. Already logged in autohosts work correctly, provided they do not log out, and non-bot users seem unaffected.

> spads.log
20180317204829 - NOTICE   - [SpringLobbyInterface] Connecting to lobby.springrts.com:8200
20180317204836 - NOTICE   - [SPADS] Lobby server default engine is Spring 104, UnitSync is using Spring 104.0.1-151-g11de57d maintenance
20180317204836 - INFO     - [SPADS] Logged on lobby server
20180317204836 - NOTICE   - [SPADS] TrueSkill service available
20180317204836 - WARNING  - [SpringLobbyInterface] Ignoring duplicate ADDUSER command for user "notAspace029"
20180317204836 - WARNING  - [SpringLobbyInterface] Ignoring duplicate ADDUSER command for user "notAspace021"
20180317204836 - INFO     - [SPADS] Channel DarkEnergy joined
20180317204836 - INFO     - [SPADS] Channel dk joined
20180317204836 - INFO     - [SPADS] Channel fi joined
20180317204836 - INFO     - [SPADS] Channel hu joined
20180317204836 - INFO     - [SPADS] Channel es joined
20180317204836 - INFO     - [SPADS] Channel se joined
20180317204836 - INFO     - [SPADS] Channel ru joined
20180317204836 - INFO     - [SPADS] Channel en joined
20180317204836 - INFO     - [SPADS] Channel fr joined
20180317204836 - INFO     - [SPADS] Channel de joined
20180317204836 - INFO     - [SPADS] Channel pl joined
20180317204836 - INFO     - [SPADS] Channel it joined
20180317204836 - INFO     - [SPADS] Channel nl joined
20180317204836 - INFO     - [SPADS] Channel pt joined
20180317204837 - WARNING  - [SPADS] Disconnecting from lobby server (broken connection detected)
20180317204837 - NOTICE   - [SpringLobbyInterface] Disconnecting from lobby.springrts.com:8200
20180317204900 - NOTICE   - [SpringLobbyInterface] Connecting to lobby.springrts.com:8200
20180317204930 - CRITICAL - [SpringLobbyInterface] Unable to connect to lobby server lobby.springrts.com:8200 (IO::Socket::INET: connect: timeout)
20180317204930 - ERROR    - [SPADS] Connection to lobby server failed

linked threads:
https://springrts.com/phpbb/viewtopic.php?f=64&t=36665&p=585361#p585361
https://springrts.com/phpbb/viewtopic.php?f=11&p=584805#p584804

**Comment by abma** [comment]
since 2018-03-18 01:05:04 it should work again.

thanks TurBoss!

**Comment by abma** [comment]
The server somehow got into an invalid internal state and send some usernames twice which spads really doesn't like (connect/disconnect spam).

these changes should make it autorecover the next time:

https://github.com/spring/uberserver/commit/bbf85ae021b80d8ae72de3c661051b0d3c56d667
https://github.com/spring/uberserver/commit/8d37f8bb0cfb1ff17910fb199cb4bfa601fa0f6a
https://github.com/spring/uberserver/commit/eda77de2957852c009d42d412f510724d45f02c7

needs some time until the changes are applied as it needs the service fully restarted.

**Comment by LordTeabag** [comment]
down again

> 20180417232441 - NOTICE   - [SpringLobbyInterface] Connecting to lobby.springrts.com:8200
20180417232441 - NOTICE   - [SPADS] Lobby server default engine is Spring 104, UnitSync is using Spring 104.0.1-151-g11de57d maintenance
20180417232441 - INFO     - [SPADS] Logged on lobby server
20180417232441 - NOTICE   - [SPADS] TrueSkill service available
20180417232441 - WARNING  - [SpringLobbyInterface] Ignoring duplicate ADDUSER command for user "RelayHostManagerList"
20180417232441 - WARNING  - [SpringLobbyInterface] Ignoring duplicate ADDUSER command for user "SLrelayMaster"
20180417232442 - WARNING  - [SPADS] Disconnecting from lobby server (broken connection detected)
20180417232442 - NOTICE   - [SpringLobbyInterface] Disconnecting from lobby.springrts.com:8200
