### ISSUE TITLE
BATTLEMUTE command cannot be called

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#258]
It's not possible for mods to call the BATTLEMUTE command, afaics. 

I think the issue is that it is missing from the (mod) access levels table https://github.com/spring/uberserver/blob/bbf85ae021b80d8ae72de3c661051b0d3c56d667/protocol/Protocol.py#L20
with the result that trying to BATTLEMUTE leads to https://github.com/spring/uberserver/blob/bbf85ae021b80d8ae72de3c661051b0d3c56d667/protocol/Protocol.py#L286

The KICKBAN command presumably suffers the same bug, but I haven't tested this.

**Comment by abma** [comment]
KICKBAN + BATTLEMUTE are part of some major refactoring:

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L3058

untested:

JSON {'BATTLEMUTE': {'username': 'usertomute'}}

also i'm not sure if the changes are applied on the server yet as some recent changes require a server restart + testing:

i.e. https://github.com/spring/uberserver/commit/1c2059da66af19862097f4c42256ba9fbaa62188

**Comment by silentwings** [comment]
Is JSON {'BATTLEMUTE': {'username': 'usertomute'}} the intended usage? Imo it is too much detail to type.

**Comment by silentwings** [comment]
maybe right click user -> battlemute to differetiate from global mute

**Comment by silentwings** [comment]
By the way - am I right in thinking that this will also mute users whilst ingame?

If so, to be effective it also needs to suppress their draw-on-map commands.

**Comment by silentwings** [comment]
Will BATTLEMUTE affect ingame chat? (I am unsure if it's best that it does or not.)

**Comment by abma** [comment]
no. it requires spad to support / read the cmd from the lobby server and then (afaik) execute a mute command inside the battle for the user.

**Comment by silentwings** [comment]
Removed in #282, channel mute can now do this
