### ISSUE TITLE
 engine 427 - 430 maintenance hangs on start - spads

### ISSUE THREAD

**Issue by LordTeabag** [spring/uberserver#259]
> 20180502084216 - NOTICE   - [SPADS] Initializing SPADS 0.12.4
20180502084219 - NOTICE   - [SPADS] Loading Spring archives using unitsync library version 104.0.1-430-g4bab202 maintenance ...

**Comment by abma** [comment]
(this is the wrong bug tracker, https://github.com/Yaribz/SPADS/issues should be correct / maybe the bug tracker from spring)
whats the output of top?
does it scan for new archives and just takes some time to finish?

how many maps/games are in springs writedir?

infolog.txt / unitsync.log should give a hint whats going on.

**Comment by LordTeabag** [comment]
it does scan but usually takes 30 - 45 seconds to complete, i have over 2000 maps
this problem only exists with maintenance  427 and 430, builds before that work fine
infolog.txt is not generated during spads boot
unitsync.log:

> [unitsync] deinitialized
============== <User System> ==============
  Spring 104.0.1-430-g4bab202 maintenance (Headless Unitsync)
    Build Environment: boost-unknown, unknown stdlib
     Compiler Version: gcc-5.4.0 20160609
     Operating System: Linux 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64
     Binary Word Size: 64-bit (native)
     Deque Chunk Size: 128
        Process Clock: std::chrono::high_resolution_clock
   Physical CPU Cores: 1
    Logical CPU Cores: 2
============== </User System> ==============
Using writeable configuration source: "/home/msi/SPADS/instanceDir/server6/springsettings.cfg"
Available log sections: VFS, ArchiveScanner, unitsync
Enabled log sections: 
Enable or disable log sections using the LogSections configuration key
  or the SPRING_LOG_SECTIONS environment variable (both comma separated).
  Use "none" to disable the default log sections.
LogOutput initialized.
Using read-write data directory: /home/msi/SPADS/instanceDir/server6/
Using read-only data directory: /home/msi/.spring/
Using read-only data directory: /home/msi/SPADS/spring/auto/104.0.1-430-g4bab202-linux64/
Using read-only data directory: /home/msi/SPADS/resources/
Scanning: /home/msi/SPADS/resources/maps
Scanning: /home/msi/SPADS/resources/games
Scanning: /home/msi/SPADS/resources/packages
Scanning: /home/msi/SPADS/spring/auto/104.0.1-430-g4bab202-linux64/base
Scanning: /home/msi/.spring/packages
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/packages/ca3dc5e8d546b609bafacbacd637fe44.sdp" already in "/home/msi/.spring/packages/ca3dc5e8d546b609bafacbacd637fe44.sdp", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/packages/12aaae7ebc679121d60f0d9d11502bcb.sdp" already in "/home/msi/.spring/packages/12aaae7ebc679121d60f0d9d11502bcb.sdp", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Mearth_v4.sd7" already in "/home/msi/SPADS/resources/maps/mearth_v4.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/speed_ball_matrix_16_way_nometal_v6.sd7" already in "/home/msi/SPADS/resources/maps/Speed_Ball_Matrix_16_Way_NoMetal_V6.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/small_supreme_islands_v2.sd7" already in "/home/msi/SPADS/resources/maps/Small_Supreme_Islands_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/terra.sd7" already in "/home/msi/SPADS/resources/maps/Terra.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/badlands.sd7" already in "/home/msi/SPADS/resources/maps/Badlands.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/deltasiegex.sd7" already in "/home/msi/SPADS/resources/maps/DeltaSiegeX.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/hikinen_ja_oksettava_kaurapuuro-5v5-v01.sd7" already in "/home/msi/SPADS/resources/maps/Hikinen_ja_Oksettava_Kaurapuuro-5v5-v01.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/moon_quartet_remake.sd7" already in "/home/msi/SPADS/resources/maps/Moon_Quartet_Remake.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Speed_Ball_Matrix_9_Way_NoMetal_V3.sd7" already in "/home/msi/SPADS/resources/maps/speed_ball_matrix_9_way_nometal_v3.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Kivekset_Halkova_Bassotaajuus-v02.sd7" already in "/home/msi/SPADS/resources/maps/kivekset_halkova_bassotaajuus-v02.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/SuperVaubanFortress.sd7" already in "/home/msi/SPADS/resources/maps/supervaubanfortress.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/ternion.sd7" already in "/home/msi/SPADS/resources/maps/Ternion.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/superspeedmetal_xtrem.sd7" already in "/home/msi/SPADS/resources/maps/SuperSpeedMetal_Xtrem.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Tempest.sd7" already in "/home/msi/SPADS/resources/maps/tempest.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Speed_Ball_Matrix_16_Way_NoMetal_V2.sd7" already in "/home/msi/SPADS/resources/maps/speed_ball_matrix_16_way_nometal_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/speedmetal.sd7" already in "/home/msi/SPADS/resources/maps/SpeedMetal.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/SpeedMetalBig.sd7" already in "/home/msi/SPADS/resources/maps/speedmetalbig.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/bluebend-v01.sd7" already in "/home/msi/SPADS/resources/maps/BlueBend-v01.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Hikinen_ja_Oksettava_Kaurapuuro-v02.sd7" already in "/home/msi/SPADS/resources/maps/hikinen_ja_oksettava_kaurapuuro-v02.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/FrozenFortress_v2.sd7" already in "/home/msi/SPADS/resources/maps/frozenfortress_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Mescaline_v2.sd7" already in "/home/msi/SPADS/resources/maps/mescaline_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/speed_ball_matrix_16_way_nometal_v3.sd7" already in "/home/msi/SPADS/resources/maps/Speed_Ball_Matrix_16_Way_NoMetal_V3.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Victoria_Crater.sd7" already in "/home/msi/SPADS/resources/maps/victoria_crater.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/small_supreme_battlefield_dry.sd7" already in "/home/msi/SPADS/resources/maps/Small_Supreme_Battlefield_Dry.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/speed_ball_matrix_16_way_nometal_v7.sd7" already in "/home/msi/SPADS/resources/maps/Speed_Ball_Matrix_16_Way_NoMetal_V7.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/talus.sd7" already in "/home/msi/SPADS/resources/maps/Talus.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Eye_Of_Horus_v2.sd7" already in "/home/msi/SPADS/resources/maps/eye_of_horus_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Brazillian_Battlefield_Remake_V2.sd7" already in "/home/msi/SPADS/resources/maps/brazillian_battlefield_remake_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Speed_Ball_Matrix_16_Way_NoMetal.sd7" already in "/home/msi/SPADS/resources/maps/speed_ball_matrix_16_way_nometal.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/mini_superspeedmetal.sd7" already in "/home/msi/SPADS/resources/maps/Mini_SuperSpeedMetal.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Titan-v2.sd7" already in "/home/msi/SPADS/resources/maps/titan-v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Curved_Focus.sd7" already in "/home/msi/SPADS/resources/maps/curved_focus.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/metalwall.sd7" already in "/home/msi/SPADS/resources/maps/MetalWall.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/parched_mesa-v03.sd7" already in "/home/msi/SPADS/resources/maps/Parched_Mesa-v03.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Escarpment-v2.sd7" already in "/home/msi/SPADS/resources/maps/escarpment-v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/parched_mesa-v04.sd7" already in "/home/msi/SPADS/resources/maps/Parched_Mesa-v04.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/deltasiegerevx.sd7" already in "/home/msi/SPADS/resources/maps/DeltaSiegeRevX.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/small_supreme_battlefield_v2.sd7" already in "/home/msi/SPADS/resources/maps/Small_Supreme_Battlefield_V2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Metal_Plate_22x22.sd7" already in "/home/msi/SPADS/resources/maps/metal_plate_22x22.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/claymore_v2.sd7" already in "/home/msi/SPADS/resources/maps/Claymore_v2.sd7", ignoring.
Error: [AS::CheckCachedData] found a "/home/msi/SPADS/resources/maps/Speed_StormSiegeDuoWet.sd7" already in "/home/msi/SPADS/resources/maps/speed_stormsiegeduowet.sd7", ignoring.

**Comment by LordTeabag** [comment]
i have cleaned up the missing files errors, 

Spring 104.0.1-430-g4bab202 maintenance, unitsync.log: 
https://pastebin.com/5NqEzUYj

Spring 104.0.1-427-g4757d3c maintenance, unitsync.log: 
https://pastebin.com/EABJAABN

Spring 104.0.1-413-gd902a7b maintenance , unitsync.log: 
https://pastebin.com/Qj1Prtmr

Spring 104.0.1-287-gf7b0fcc maintenance, unitsync.log: 
https://pastebin.com/LfqszLrQ

**Comment by abma** [comment]
could be https://springrts.com/mantis/view.php?id=5294

still this is the very wrong bug tracker. IMHO https://springrts.com/phpbb/viewforum.php?f=88 is for now the correct place.

**Comment by rtri** [comment]
427-g4757d3c and above use SHA archive hashes which are (much) slower to calculate.
