### ISSUE TITLE
add cleanup x times a day

### ISSUE THREAD

**Issue by abma** [spring/uberserver#263]
+ run cleanup when error is found

just a workarround for an other issue, but... :-|

**Comment by abma** [comment]
these checks already exists: i guess its best to not allow to reconnect very fast (which seems to causes issues with duplicate users)

**Comment by abma** [comment]
for the beginning: 5 seconds?!

**Comment by abma** [comment]
better: run it daily

**Comment by silentwings** [comment]
what about having two cleanup functions, internally?

one that runs daily and does generic cleaning up the db tasks (deleting expired bans/verifications, unwanted user accounts, checking for new spring versions, etc)

one that runs only at CLEANUP and does stuff that we think helps with unfixed bugs/crashes, plus calls the first one

**Comment by abma** [comment]
+1 ;-)

**Comment by silentwings** [comment]
triggering this inside the server seems a little unclean, because afaics it would have to be triggered from inside twisted (a separate thread can't be used, ofc)

perhaps an admin bot that sends the commands would be best?

**Comment by silentwings** [comment]
I'm not sure where to trigger a daily task from!
