### ISSUE TITLE
implementation of email verification

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#265]
Since its been asked/discussed for a while, I worked out a plan for doing it, in two stages:

(1) Require that the response to REGISTER has a third parameter, a valid email address (i.e.  fix #165). No fancy validity checks, just a regex and a check that the email isn't already registered. If a valid email address is not entered, return a suitable error message in REGISTRATIONDENIED.

(2) After REGISTRATIONACCEPTED is sent, wait 30 seconds (or suchlike) and then send a no-reply email containing a short verification code to the email address given. Require that this code be sent back as the first parameter to CONFIRMAGREEMENT (after the usual LOGIN->AGREEMENT-> sequence). Send DENIED/ACCEPTED and proceed as normal.

Compatibility would require two small pieces of extra behaviour from lobbies:
(1) an email address field alongside registration
(2) a verification code field alongside ToS agreement
Afaics this is minimal; lobbies would already react correctly in cases of accidentally stopping half-way through registration, if smth is denied, etc.

Lobbies that remained incompatible would be unable to register new user accounts (and would report suitable errors via REGISTRATIONDENIED/DENIED, requiring no additional code), but would otherwise be unaffected.

Before I go ahead and implement, can I check that this design would be both wanted/functional.

**Comment by silentwings** [comment]
I have now implemented everything exccept threading - response please.

**Comment by silentwings** [comment]
1 - I was thinking more it might deter some (but not all) serial offenders from cat/mouse games
2 - good idea, will do
3 - users trying to login without a verified email will be given the user agreement + option to re-enter code
4 - for the moment, I'd like to keep effort required from lobby devs at a minimum, at least until someone from SL dev shows an interest in doing this

**Comment by silentwings** [comment]
Turns out the addition of CONFIRMAGREEMENTACCEPTED/DENIED are unnecessary because the lobby protocol docs are wrong, and what is actually expected is a DENIED/ACCEPTED (in response to the LOGIN)

It's all implemented locally now, and tested.

**Comment by abma** [comment]
can you be more specific whats wrong in the docs?

atm it is:
REGISTER -> REGISTRATIONACCEPTED / REGISTRATIONDENIED
LOGIN -> AGREEMENT + AGREEMENTEND
CONFIRMAGREEMENT -> ACCEPTED

**Comment by abma** [comment]
when an account is fully registered login is
LOGIN -> ACCEPTED / DENIED

**Comment by TurBoss** [comment]
> I can update the docs, if wanted, but I don't know what gives access to edit https://springrts.com dl/LobbyProtocol/, or if I already have access, etc etc.

https://github.com/spring/LobbyProtocol

**Comment by silentwings** [comment]
Got fed up of waiting, https://github.com/silentwings/uberserver/commit/ca2ae13648abf8cdbeac3e4b8f76664ff0ced607

**Comment by specing** [comment]
Unfortunately I was not watching this repo and missed the whole discussion from start to finish, but here is some feedback from me:

- I currently own 20 accounts, mostly for autohost purposes. How will one be able to register such additional accounts if a single email address can only be used once? 
- Could this registration procedure also be simplified, such that the user can e.g. click on a link in email to confirm?
- Lobbies that remained incompatible: The DENIED message could feature "Your lobby is too old, please update. If updating is not possible, go here <https://somewebbasedregisterform to register".

PS: while we are updating the REGISTER command, I'd highly suggest changing password hash from md5 to something more suitable.

**Comment by gajop** [comment]
> I currently own 20 accounts, mostly for autohost purposes. How will one be able to register such additional accounts if a single email address can only be used once?

I'd suggest implementing a way to link bots to accounts (this now suddenly gets a lot more complicated), which could be done via email.
Register a bot (while specifying the owner username) -> get a confirmation email -> click on the link. Bot is linked to account. Obviously you'd need to have an account but that's a reasonable assumption.

> Could this registration procedure also be simplified, such that the user can e.g. click on a link in email to confirm?

Agreed.

> PS: while we are updating the REGISTER command, I'd highly suggest changing password hash from md5 to something more suitable.

I am generally against any change there that would require me to run and implement SHA (or whatever new system) in Lua so Chobby would work again (thankfully I *am* paying attention to this repository). I understand the security concerns of using MD5 for this purpose, but I'd rather we just use SSL (and implement SSL support in engine luasockets), than try to provide "security" over an inherently unsecure channel.

> PPS: It would have been better to discuss the implementation of this in the forums, as it affects a lot of projects.

Agreed, at least as far as outlining the specification (implementation can be exclusive to Github)

**Comment by silentwings** [comment]
| Could this registration procedure also be simplified, such that the user can e.g. click on a link in email to confirm?
Not by me, because it is not worth the extra work.

| How will one be able to register such additional accounts if a single email address can only be used once?
Eventually, *all* users will be expected to have only one account. 

Any additional accounts required for auto-hosting will need to be created by moderators. If this is not implemented by the time a release occurs, the requirement for unique email addresses will be temporarily relaxed.

**Comment by specing** [comment]
@gajop this is not about secure transport, this is about how passwords are stored in database. While I must admit that I have not looked into what uberserver does with the md5 (if it applies pbkdf or something similar ontop), storing md5 password + email is great for disaster when that database eventually leaks.

**Comment by gajop** [comment]
@specing huh, yes. i just assumed it was stored with bcrypt or something similar...
