### ISSUE TITLE
allow chatbots to speak for / show users directly

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#274]
random idea -- a command to be used by irc-link-ish bots, 

format
`SAYFROM location channel username message`
and resulted in
`[timestamp] <username@location> message`
appearing in the target channel (in which the bot would be required to be present). Corresponding SAIDFROM command also needed.

It avoids having the name of the bot, which is not useful info, being printed into the chatlog, and would allow a single (trusted) bot to cleanly bridge communication with multiple external versions of a channel.
`[09:46:47] <Nightwatch> <ivand#0978> Can anyone advise on Custom Units Shaders?`
vs
`[09:46:47] <ivand@Discord> Can anyone advise on Custom Units Shaders?`
Would also allow channel mutes to be applied to users messaging from external channels.

Would also have 
`JOINFROM location channel username`
`LEAVEFROM location channel username`
too, and show e.g. `ivand@discord` in the channel user list (and external channels could do whatever they saw fit with such info). This would avoid channels looking empty when they aren't!

**Comment by TurBoss** [comment]
its a fantastic idea for what I'm working on
:dagger: Glenda :dagger:

**Comment by TurBoss** [comment]
this is also useful for battle rooms when users talk ingame

**Comment by silentwings** [comment]
I don't think so, because we couldn't e.g. run an uberserver isntance on Discord or on the ZK server.

**Comment by silentwings** [comment]
I'm going to start work on this, but I plan for it to come after the batch of changes that is currently waiting to go live.

> this is also useful for battle rooms when users talk ingame
The server views battles and channels as qwuite a bit different. I think it is best to implement this for channels first -- I think it would be best to fix #58 before/whilst doing a battle version of this ticket (and I wonder if #58 can be done via a shorter route than discussed in its ticket).

**Comment by silentwings** [comment]
Is it safe to assume that only _one_ bridging bot will exist for each external location (e.g. one bot for Discord, one bot for ZK, one bot for IRC, etc -- with each bot handling multiple channels)? This makes saner code, and seems reasonable to me.
