### ISSUE TITLE
some changes from Send to RealSend should be reverted

### ISSUE THREAD

**Issue by abma** [spring/uberserver#276]
6f73ea5cb738c159e2ff94c6d030cc98b51bbc1e

changing Send to RealSend very likely breaks stuff.

**Comment by abma** [comment]
same for bf70e6b66b32ce4145622eefe99087b55275fce6

**Comment by abma** [comment]
@silentwings

**Comment by silentwings** [comment]
Is there a reason why they can't just all be Send calls? 

(I used RealSend in case there was. Or maybe there is something more subtle that I'm mis-understanding here - I couldn't see why RealSend was being used, so was scared to remove it.)

**Comment by abma** [comment]
RealSend is unbufferd vs Send is buffered

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L978

**Comment by silentwings** [comment]
I noticed that changing Send to RealSend will break use of msg ids with the cmds involved.

I think the buffer is affected because after login there is over is no buffering anymore - https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L978

**Comment by abma** [comment]
in short: in _SendLoginInfo() RealSend must be used
https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L1013 ->
https://github.com/spring/uberserver/blob/master/Client.py#L231

**Comment by silentwings** [comment]
ok, revert.
