### ISSUE TITLE
rename latest version to min version

### ISSUE THREAD

**Issue by abma** [spring/uberserver#278]
...

**Comment by abma** [comment]
don't forget the docs!

**Comment by silentwings** [comment]
i'll take this one on - essentially, unhardcode https://github.com/spring/uberserver/commit/90cb0f96fcf8238b9b55c695f2e7966ce722b592

**Comment by abma** [comment]
> At request of engine devs, who will also choose which Spring version is the current minimum. (Default will typically be the latest major release.)

IMHO should be similar to how the latest version was set.
only the delay will be larger, depending on the required changes.

sth. like:
"Spring 104.0 as it will be set as minimal version on lobbyserver on Tuesday, 03. October if no blocking bug is found. Download links will be updated then as well."

means basicly the engine devs will decide which surely will listen to game devs.

**Comment by abma** [comment]
hu? KISS?!

calling SETMINSPRINGVERSION should instantly set the min version.

**Comment by silentwings** [comment]
I think we are talking at cross purposes here.

My plan is that when SETSPRINGVERSION is called the effect will be to 
(1) Immediately set the latest min spring version (which is checked for in OPENBATTLE).
(2) Automatically close all currently open battles that would now fail the min version requirement.

Clearly (1) is necessary. The question is whether to do (2) at the same time.

**Comment by silentwings** [comment]
I changed my mind a few times ... end result is #280
