### ISSUE TITLE
LEAVE channel doesn't respond

### ISSUE THREAD

**Issue by abma** [spring/uberserver#283]
it should respond to the sender with LEFT, too (as all other commands do)

maybe see https://github.com/springlobby/springlobby/issues/894

(lobby protocol doc needs to be adjusted as well)

**Comment by abma** [comment]
usually a good style is when the docs are shot. exceptions makes docs long :-P

**Comment by silentwings** [comment]
I'll fix this, turns out I actually need it for #58
