### ISSUE TITLE
should registrations via VPNs be forcibly delayed?

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#288]
E.g. A client who registers via an IP detected as a VPN, could be made to wait before theirverificiation code is sent. They could be (instantly) sent a first email saying that a VPN was detected, so the delay was imposed.

(This deliberately allows a user who registered an account on a normal IP, to later login with this same account via a VPN, without any issue. Hopefully this would avoid bothering legit users of VPNs too much.)

@abma: It could be done with e.g. the free service of https://iphub.info/, but I wonder if detection is reliable enough. Obvious intention is to increase the effectiveness of server bans. Thoughts?

**Comment by gajop** [comment]
Ideally the email should be instantaneous, but after they active it, they should get another email telling them to wait for manual approval because a VPN was detected. And/or maybe ask them to write out their request and clarify why they need to use a VPN.

**Comment by abma** [comment]
how to detect vpn?

**Comment by gajop** [comment]
ZK devs shared their implementation with me once: 
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/f15710406ddd448dfe30970978a299859a2df4cd/ZkLobbyServer/LoginChecker.cs#L260

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/5ddec86591302bf858ac6c2f1e362a46952f0235/Shared/PlasmaShared/Whois.cs

With this data https://pastebin.com/0BcFi18k & https://pastebin.com/DAQJs9DQ

**Comment by gajop** [comment]
There's apparently a better (cleaner) format of the blocked hosts, but we'd have to ask @Licho1 or someone else with access about it.

**Comment by silentwings** [comment]
All ZK are doing there is querying an external VPN detection service - which is what I'd suggested as well. https://iphub.info/api looks good.

**Comment by silentwings** [comment]
Perhaps it would be sensible to first implement just the detection part, with no delays, and with the result printed into #moderator alongside current info, to see how well it works?

**Comment by silentwings** [comment]
> wait for manual approval because a VPN was detected
I would rather leave waiting for manual approval until there is some prospect of doing it via a website (e.g. by linking forum/lobby accs). I think a delay is a reasonable compromise until then.
