### ISSUE TITLE
self.verificationdb + getVerificationDB() possible breaks reload as old references are kept it seems

### ISSUE THREAD

**Issue by abma** [spring/uberserver#296]
there should be no direct reference kept: self.userdb or root.getUserDB() must be used!

**Comment by silentwings** [comment]
I think the issue is that the verificationdb needs a new sessionmaker (alongisde e.g. https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L2916)

**Comment by abma** [comment]
sorry, was in a hurry. i'm not sure about that: it just looks like the references kept to SQLUsers could cause problems with reloading: this should be checked.

**Comment by silentwings** [comment]
I've tested but I haven't found a way to cause an error here.
