### ISSUE TITLE
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'channels.topic_user_id' in 'field list'") 

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#300]
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
>     context)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
>     cursor.execute(statement, parameters)
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
>     self.errorhandler(self, exc, value)
>   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorvalue
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
>     res = self._query(query)
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
>     rowcount = self._do_query(q)
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
>     db.query(q)
>   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
>     _mysql.connection.query(self, query)
> _mysql_exceptions.OperationalError: (1054, "Unknown column 'channels.topic_user_id' in 'field list'")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "server.py", line 57, in <module>
>     _root.init()
>   File "/home/lobby/uberserver/DataHandler.py", line 118, in init
>     channels = self.channeldb.all_channels()
>   File "/home/lobby/uberserver/SQLUsers.py", line 1098, in all_channels
>     for chan in response:
>   File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
>     return self._execute_and_instances(context)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
>     return meth(self, multiparams, params)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
>     compiled_sql, distilled_params
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
>     context)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
>     exc_info
>   File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
>     context)
>   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
>     cursor.execute(statement, parameters)
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
>     self.errorhandler(self, exc, value)
>   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorvalue
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
>     res = self._query(query)
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
>     rowcount = self._do_query(q)
>   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
>     db.query(q)
>   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
>     _mysql.connection.query(self, query)
> sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'channels.topic_user_id' in 'field list'") [SQL: 'SELECT channels.id AS channels_id, channels.name AS channels_name, channels.`key` AS channels_key, channels.owner_user_id AS channels_owner_user_id, channels.topic AS channels_topic, channels.topic_time AS channels_topic_time, channels.topic_user_id AS channels_topic_user_id, channels.antispam AS channels_antispam, channels.autokick AS channels_autokick, channels.censor AS channels_censor, channels.antishock AS channels_antishock, channels.store_history AS channels_store_history \nFROM channels']

**Comment by abma** [comment]
FYI:
2019-01-28 08:40:48 INFO  server.<module>:40  Starting uberserver...
