### ISSUE TITLE
relayhost host with spring engine version '*' / remove 'cl' flag

### ISSUE THREAD

**Issue by abma** [spring/uberserver#301]
for some reason, this version can't be downloaded ;-)

who removed the default version?

**Comment by abma** [comment]
https://github.com/spring/uberserver/commit/6cdb02b2573f9f06fb8f7561f0a05a82a069771b#diff-cb20f5e10bd02a72b1e7fb935fcacbb5L29

**Comment by abma** [comment]
"cl" compat flag is mandatory it seems since the latest changes
https://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#OPENBATTLE:client

" cl: added Engine Name / Engine Version to BATTLEOPENED/ OPENBATTLE "

**Comment by abma** [comment]
'cl' flag + all references to it needs to be removed (as some other changes will soon break / or already broke old lobbies)

**Comment by silentwings** [comment]
I think the compatibility code for 'cl' still exists? https://github.com/silentwings/uberserver/blob/master/protocol/Protocol.py#L1729

The protocol docs only specify the current version of the protocol - with the exception of the changelog which brief explains some of the older compat flags.

**Comment by abma** [comment]
as i already wrote: the cl flag needs to die

**Comment by silentwings** [comment]
Ok, I think we might have meant the same thing ;)

**Comment by silentwings** [comment]
I don't think there is anything wrong in the server code here; just relay hosts need a fallback to deal with '*' as min spring version (meaning: no min spring version is currently set).

**Comment by silentwings** [comment]
#328
