### ISSUE TITLE
in_CLEANUP should be (partly) removed

### ISSUE THREAD

**Issue by abma** [spring/uberserver#303]
as it causes inconsistency when called when a user is currently logging in.

**Comment by abma** [comment]
maybe reduce it to consistency checking, i.e. remove all del / remove() commands

**Comment by silentwings** [comment]
Nice catch

**Comment by silentwings** [comment]
I think we can't do this until #290 is fixed

**Comment by silentwings** [comment]
afaics code path for this is _SendLoginInfo -> self.clientFromSession  -> cleanup
happens during sending battles info, triggered by a battle containing a session_id that is not in _root.clients

**Comment by silentwings** [comment]
I've given this some thought but I haven't managed to think of a way that an inconsistency can actually result.

**Comment by silentwings** [comment]
I think the worst that can happen here is that, if an existing inconsistency exists (=invalid session_id in battle, causes battle to be closed once deleted) the client which triggers cleanup on login will be left dangling in the middle of the login info.
