### ISSUE TITLE
SPADS hosts choose to disconnect after launching spring

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#314]
needs a logfile from an autohost owner...

**Comment by silentwings** [comment]
20190215112356 - INFO     - [SPADS] Logged on lobby server
20190215112356 - INFO     - [SPADS] Channel s44games joined
20190215112356 - INFO     - [SPADS] Channel s44 joined
20190215112356 - INFO     - [SPADS] Channel main joined
20190215112408 - NOTICE   - [SPADS] TrueSkill service available
20190215121625 - INFO     - [SPADS] File "/data/users/s44/spads/var/WorldAtWarII_rapid2/preferences.dat" dumped
20190215121625 - INFO     - [SPADS] File "/data/users/s44/spads/var/WorldAtWarII_rapid2/mapHashes.dat" dumped
20190215121626 - INFO     - [SPADS] File "/data/users/s44/spads/var/WorldAtWarII_rapid2/userData.dat" dumped
20190215131627 - INFO     - [SPADS] File "/data/users/s44/spads/var/WorldAtWarII_rapid2/preferences.dat" dumped
20190215131627 - INFO     - [SPADS] File "/data/users/s44/spads/var/WorldAtWarII_rapid2/mapHashes.dat" dumped
20190215131628 - INFO     - [SPADS] File "/data/users/s44/spads/var/WorldAtWarII_rapid2/userData.dat" dumped
20190215132634 - WARNING  - [SPADS] Unable to get skill of player Sanguinario_Joe #55613 (unrated account)
20190215133334 - ERROR    - [SpringLobbyInterface] Ignoring LEFT command (non joined channel:"__battle__958549")
20190215133335 - WARNING  - [SPADS] Disconnecting from lobby server (broken connection detected)
20190215133335 - NOTICE   - [SpringLobbyInterface] Disconnecting from lobby.springrts.com:8200

**Comment by abma** [comment]
SPADS is touchy: very likely it sees for some reason an inconsistent state. Its solution is to disconnect and reconnect to "fix" the problem.

**Comment by silentwings** [comment]
yep!

https://github.com/spring/uberserver/commit/f6e4ac6f92a1306ccb37cfdd1f9cb4993b32be18
