### ISSUE TITLE
IRC clients spamming login attempts

### ISSUE THREAD

**Issue by nixtux** [spring/uberserver#315]
[16:25] -irc.springrts.com- *** Login denied on lobby server (You are banned: (login/registration spam), 29 days remaining)
Current system seems a bit too over zealous, by irc client auto reconnects every 5 sec. 
Also should moderators not be immune to auto system bans?

**Comment by silentwings** [comment]
I've removed the ban that caused this but I'm unsure if this was the result of a bug in the server or in the client.

The ip 78.46.100.157 was banned for spamming login attempts with incorrect username and password. Was that you?

**Comment by nixtux** [comment]
I think it's my connect attempts, well my irc client trying to use a second user name if first fails.

**Comment by silentwings** [comment]
I'm still not sure exactly what's wrong here

>  irc client auto reconnects every 5 sec.

Does it do this even if you are logged in?

**Comment by abma** [comment]
78.46.100.157 is springrts.com :-)

**Comment by silentwings** [comment]
Hmm, I guess a more serious issue is that if the whole IRC bridge comes via this IP, one user spamming failing registrations can block the whole bridge.

I think the best way to fix this is for the IRC bridge to go via the matrix / bridge interface!

**Comment by silentwings** [comment]
Unfortunately this relates to the IRC protocol translation and not the "true" bridge - so this issue still stands

A few IRC clients spam hundreds of failing login attempts, still, often without even a valid username

**Comment by abma** [comment]
https://springrts.com/phpbb/viewtopic.php?f=71&t=39345

**Comment by silentwings** [comment]
probably best to change anything (sadly)
