### ISSUE TITLE
Hosting a game from springlobby with relayhost not working

### ISSUE THREAD

**Issue by baracoder** [spring/uberserver#330]
SpringLobby 0.267
1. Host new...
2. 

```
[20:36:41] <SLrelaySlave1> Engine version my-game isn't installed on the relayhost. Available versions are: 
[20:36:41] <SLrelaySlave1> 104.0
```

`my-game` is the description of the battle

**Comment by abma** [comment]
i guess the error message is wrong XD

did you select 104.0 as engine version when hosting?

**Comment by abma** [comment]
err, springlobby update needed: https://github.com/springlobby/springlobby/commit/12edf2c65bd5297fe6b9d2b9cce34c96990e753a

**Comment by baracoder** [comment]
Confirmed, works with current master branch.
