### ISSUE TITLE
SQL string filters fail to be case sensitive

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#335]
for example, in SQLUsers.UsersHandler

```
def clientFromUsername(self, username):
	entry = self.sess().query(User).filter(User.username==username).first()
	if not entry: return None
	return OfflineClient(entry)
```

Calling this with username=='[fx]bluestone' returns the offline client with username [Fx]Bluestone

On the Python side (e.g. using == with DataHandler.usernames) there is case sensitivity

This likely causes inconsistencies

**Comment by silentwings** [comment]
Easiest way to test this: send "GETUSERINFO [fx]bluestone" when [Fx]Bluestone is offline
(and if the client is online, with incorrect case there will be a crash caused by this bug!)

**Comment by abma** [comment]
> Calling this with username=='[fx]bluestone' returns the offline client with username [Fx]Bluestone

doesn't that mean, that the search is case sensitive but the search should be case insensitive?

**Comment by abma** [comment]
https://stackoverflow.com/questions/16573095/case-insensitive-flask-sqlalchemy-query

->

.query.filter(Model.column.ilike("ganye"))

-> 	entry = self.sess().query(User).filter(User.username.ilike(username)).first()

should do the trick
(untested)

**Comment by abma** [comment]
ugh:
https://stackoverflow.com/questions/22172727/how-to-force-a-filter-to-match-exact-cases-case-sensitivity-in-sqlalchemy/31788828

entry = self.sess().query(User).filter(User.username == func.binary(username)).first()

**Comment by abma** [comment]
better:

assert(
entry = self.sess().query(User).filter(User.username.ilike(username)).first()

**Comment by silentwings** [comment]
https://stackoverflow.com/questions/40897701/mysql-transform-case-sensitive-unique-field-into-unique-case-insensitive-field?rq=1

**Comment by silentwings** [comment]
https://www.oreilly.com/library/view/mysql-cookbook/0596001452/ch04s10.html

"String comparisons in MySQL are not case sensitive by default:"

This seems a legitimate case in which to blame MS...

**Comment by silentwings** [comment]
http://crazedmonkey.com/blog/links/sqlalchemy-does-not-force-case-sensitive-matching-for-mysql-or-any-other-dbs.html

Seems the issue is our col types are wrong, utf8 defaults to utf8_general_ci which is case insensitive, and utf8_general_cs is needed for case sensitivity

**Comment by silentwings** [comment]
resolution is that:
- username is case sensitive but case insensitivity on db side prevents registration of a second user with "same" name in different case
- functions which retrieve user by username (from db) and require a case sensitive check must also check the case on python side (primarily clientFromUsername)
- user trying to login with incorrect case gets a error msg with username containing correct case
