### ISSUE TITLE
relayhosts won't work (until SL is updated)

### ISSUE THREAD

**Issue by Hexxitfan111** [spring/uberserver#339]
When I try to host a battle like so:
![image](https://user-images.githubusercontent.com/35806451/54954182-0d274e80-4f18-11e9-9456-df8b36db238d.png)
The lobby proceeds to throw the following error:
![image](https://user-images.githubusercontent.com/35806451/54954222-24663c00-4f18-11e9-95d3-19952f2c9482.png)
It appears that the lobby thinks the battle name is the engine version. When I name the battle 104.0, then i get no errors and nothing happens.

**Comment by abma** [comment]
this needs a changed springlobby, sorry.

see #908 and https://github.com/springlobby/springlobby/commit/12edf2c65bd5297fe6b9d2b9cce34c96990e753a

-> for windows a new release needs to be made

i leave this issue open until a release is made as i guess some more people will hit this bug. :-|

**Comment by silentwings** [comment]
fyi, the issue is with relayhosts, self-hosted battles work

**Comment by MasterBel2** [comment]
If this issue is relying on SL, maybe provide a label that describes it as so?
