### ISSUE TITLE
xmlrpc down

### ISSUE THREAD

**Issue by TurBoss** [spring/uberserver#348]
the xmlrpc interface is no longer working

**Comment by silentwings** [comment]
up again but i haven't yet looked into what caused it to go down

**Comment by TurBoss** [comment]
thanks

its working

**Comment by TurBoss** [comment]
was working until I did visit this link
https://replays.springrts.com/xmlrpc/

**Comment by abma** [comment]
the cause afaik was:

root@spring1:/etc# git diff 902e5ac6a1619ba98676c97c17f0cdf9b62a43ab ba5fd255776899125151572b7bb71b74b70d712e hosts
diff --git a/hosts b/hosts
index e3b97a9..a00e2d5 100644
--- a/hosts
+++ b/hosts
@@ -1,6 +1,5 @@
 127.0.0.1      localhost
-127.0.1.1      spring1
-127.0.2.1      springrts.com
+127.0.1.1   spring1
 ::1            localhost ip6-localhost ip6-loopback
 fe00::0                ip6-localnet
 ff00::0                ip6-mcastprefix

**Comment by TurBoss** [comment]
thats for sure my fault
thanks
