### ISSUE TITLE
require email verif, release new SL, activate chat bridges, deprecate old lobby flags, etc

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#353]
https://springrts.com/phpbb/viewtopic.php?f=64&t=40355 suggests that SWL no longer requires support, so seems good to go

will link in the various tickets involved when time permits

**Comment by ForbodingAngel** [comment]
In that thread I waxed somewhat eloquent about how I have no possibility to distribute on linux at the moment (with chobby). That said, I am ok with temporarily dropping linux support until a solution is reached. Please just let me know beforehand though with some warning.

**Comment by abma** [comment]
a springlobby release is required which is/was blocked by https://github.com/springlobby/springlobby/issues/920

**Comment by silentwings** [comment]
#328 
https://github.com/springlobby/springlobby/pull/918
https://github.com/springlobby/springlobby/pull/916
https://github.com/springlobby/springlobby/pull/909

**Comment by silentwings** [comment]
Your SWL package will break before this ticket ever comes into play - it will break as soon as SL is updated because at that point the server will (be configured to) require email verification on registration. 

So - it is https://springrts.com/phpbb/viewtopic.php?f=92&t=40429&p=592886#p592886 that you should watch for a date on.

**Comment by abma** [comment]
springlobby is released, so most users should have updated soon to springlobby 0.268 -> email verification could be enabled in a few days.

**Comment by F1ll3r** [comment]
what is the plan to do with already created accounts?

e.g. my account passwort currently does not work anymore and admins cant reset..
https://springrts.com/phpbb/viewtopic.php?f=11&t=40135&p=592346#p592346

**Comment by silentwings** [comment]
> what is the plan to do with already created accounts?
lobby moderators can reset a users password and have the new (randomly generated) password sent by email (using RESETUSERPASSWORD)

if the user did not register an email address then the lobby moderator can also specify the email address, provided they are confident of the users claimed identity

**Comment by silentwings** [comment]
done pending server restart
