### ISSUE TITLE
Slow (>10sec) to connect

### ISSUE THREAD

**Issue by rosscosack** [spring/uberserver#363]
Uberserver on BAR server (road-flag.bnr.la) is slow to accept user connection attempt from springlobby (only; Chobby is immediate).
Log shows uberserver acknowledges connection attempt immediately (when tailed), then in this instance there is a 24 sec delay until connection
```
2020-01-07 21:24:00 INFO  Protocol._new:280  [7] Client connected from <IP>:51086
2020-01-07 21:24:24 INFO  Protocol._SendLoginInfo:1039  [7] <rossco> logged in (access=admin).
```
[Full Log](https://github.com/spring/uberserver/files/4030179/server.log)

delay as reported by SL is (in this instance) 14sec (has been approx 26 often lately)
```
[20:16:45] ** Server ** Connecting to server road-flag.bnr.la:8200...
[20:16:59] ** Server ** Connected to road-flag.bnr.la:8200.
```
 There seems to be an issue with my implementation of uberserver; connections to the BA server springfightclub and official server happen immediately.

Network lag is not an issue, there is very little lag from player to host (host is on same server as uberserver) 

I have tried several different versions of uberserver, currently I'm on `a258db83` and I have tried release 0.38 `1fa86d61`

I tried creating server.key certification (although it isn't mentioned in the docs) using certificate.py and it didn't fix it. 

SSL has me the most suspicious, it is possible I have done something wrong here and it is not a uberserver problem but am unsure how to proceed.

**Comment by abma** [comment]
atm i can only guess: is dns configured probably at the server?

i.e. reverse lookups work correct?

**Comment by rosscosack** [comment]
I think so, ping road-flag and road-flag.bnr.la resolve immediately from the server and client.
Is this what you mean by reverse lookup?

**Comment by abma** [comment]
reverse lookup is i.e.: "dig -x 185.143.163.228"

should return immediately sth. like that:
;; ANSWER SECTION:
228.163.143.185.in-addr.arpa. 86245 IN	PTR	185.143.163.228.r.toneticgroup.pl.

is the load on the server maybe high? i.e. db access could lead to delays, too if the server is swapping.

"free -m" is your friend


from the logfile some logins seems instant, i.e.:

2020-01-07 01:54:04 INFO  Protocol._new:280  [19] Client connected from ....
2020-01-07 01:54:05 INFO  Protocol._SendLoginInfo:1039  [19] <...> logged in (access=user).



are you using sqlite or mysql as db backend?

**Comment by abma** [comment]
just some other guess:

64 bytes from road-flag.bnr.la (112.213.34.51): icmp_seq=30 ttl=51 time=316 ms

is the server connected via some DSL/Cable/WiFi connection? the latency is very high. or is it just in a country far away from here? :-)

when a client connects a lot of packets are sent in both directions: this could explain the delay.

i.e. 30 * 300 ms are already 9 seconds delay. idk how many packets are sent to connect, but IMHO a lot:

some incomplete list
tcp handshake 3
server greeting 2 (TASServer ... + ACK)
STLS maybe 10
LOGIN 2
LOGININFO maybe 40
USERLIST maybe 30


its not this easy, as i.e. the tcp window size heavily influences this. but this maybe gives an idea whats the reason for the delay.

**Comment by abma** [comment]
road-flag.bnr.la seems to use TLS 1.3 vs springrts.com TLS 1.2.

idk what changed with TLS 1.3, maybe some new bug?!

maybe the server has to few entropy available, maybe it blocks because of that?

output of dmesg maybe gives a hint.

**Comment by rosscosack** [comment]
Dig response is fine 
```
;; ANSWER SECTION:
51.34.213.112.in-addr.arpa. 43102 IN	PTR	road-flag.bnr.la.
```
free -m
```
              total        used        free      shared  buff/cache   available
Mem:            733         281         220           5         231         329
Swap:             0           0           0
```
Regarding the immediate connections, this could be from Chobby - Chobby is immediate (which make me think there are no server performance issues)

Using a mysql db

the server is in Australia (as am I), there does not appear to be network issues, when I connect to springfightclub in US it's immediate

**Comment by rosscosack** [comment]
> 
> 
> road-flag.bnr.la seems to use TLS 1.3 vs springrts.com TLS 1.2.
> 
> idk what changed with TLS 1.3, maybe some new bug?!
> 
> maybe the server has to few entropy available, maybe it blocks because of that?
> 
> output of dmesg maybe gives a hint.

I think you are right
[dmesg.txt](https://github.com/spring/uberserver/files/4032823/dmesg.txt)

**Comment by rosscosack** [comment]
Are you able to determine the version of springfightclub.com:8200 or tell me how because if it's TLS 1.2 then this would firm up that this is our issue

**Comment by rosscosack** [comment]
Disabling UFW did not work, I mis-read the dmesg log, it's just the firewall

**Comment by rosscosack** [comment]
springfightclub is TLS 1.2 so I think this is the issue.
The version at road-flag is from the latest ubuntu archives, should look into how to downgrade or should springlobby be updated?

**Comment by rosscosack** [comment]
installing libssl-dev fixed it
```
The following packages will be REMOVED:
  libcurl-openssl1.0-dev libssl1.0-dev
The following NEW packages will be installed:
  libssl-dev
```

**Comment by silentwings** [comment]
Perhaps worth noting that Chobby does not use TLS when it connects. This is the only difference I can think of between Chobby/SL connections.

**Comment by rosscosack** [comment]
makes sense thanks

**Comment by rosscosack** [comment]
Could SL be waiting for a timeout before trying TLS 1.3?

**Comment by silentwings** [comment]
An idea:

turn on the debug prints at
https://github.com/spring/uberserver/blob/master/Client.py#L126
https://github.com/spring/uberserver/blob/master/Client.py#L219
and use the latest commit (in which i added timing info to them), then get a server.log of the delay happening and post that here.

Seeing the times at which the various commands are being sent may show if TLS is to blame or not.

**Comment by silentwings** [comment]
Result of doing the above on my local uberserver (but airbnb wifi...) is here https://pastebin.com/KKYFFKd9.

It shows a delay after uberserver sends TASSERVER. Springlobby then sits and wait for approx 30 secs until SpringLobby sends a PING, then PONG is replied instantly and only then does SpringLobby (instantly) send a LOGIN

**Comment by silentwings** [comment]
Aha... uberserver is sending TASSERVER twice, and the second time is out of sequence, this is perhaps a combination of (1) that as a server bug, (2) SL not having completed its TLS handshake when it happens, triggering Stop() in https://github.com/springlobby/springlobby/blob/master/src/tasserver.cpp#L542

**Comment by silentwings** [comment]
Reading SL code, without testing, seems to trace this back to wxwidgets sockets. Looks like the (second) TASSERVER command sits around waiting until a wxSOCKET_CONNECTION https://github.com/springlobby/springlobby/blob/97b8fb6030723ef2ef994a52873edeb9fb23cf56/src/socket.cpp#L66, the SL sends a PING, server responds with PONG, and this the triggers wxSOCKET_INPUT which empties the buffer and consequently processes TASSERVER which then causes it to finally try and log in.

**Comment by abma** [comment]
could be this: https://github.com/openssl/openssl/issues/7327

**Comment by abma** [comment]
meh, seems to be a bug in springlobby, the test client instantly returns "PONG" when using tls1.3:

https://github.com/spring/uberserver/commit/5ff6ffe11f4511486d7eec068518b669e128ac87
