### ISSUE TITLE
current channel list contains __battle__67292

### ISSUE THREAD

**Issue by abma** [spring/uberserver#364]
looks like an error?!

to reproduce, in springlobby tools->channel list and search for battle

**Comment by abma** [comment]
when trying to join it:

Failed to join channel #Channel. '__battle__67292' is associated to a battle, please use JOINBATTLE to access it

**Comment by silentwings** [comment]
its a channel that is part of a battle, it can't be joined without joining the battle (and then joining is automatic)

probably SL should hide channels with the __battle__ prefix from its displayed channel list, these are reserved channel names

**Comment by abma** [comment]
ok, then why is only one battle listed?

**Comment by silentwings** [comment]
because the rest haven't been registered (they are unregistered channels until !register is used)

**Comment by silentwings** [comment]
[21:35:25] <ChanServ> #__battle__67292 info: Anti-spam protection is off. Founder is <[Fx]Bluestone>. Operator list is empty. Currently contains 1 users and 0 bridged users. 

it was me :D the test battle

**Comment by abma** [comment]
the battle doesn't exist any more?!

**Comment by silentwings** [comment]
the channel persists, that's ok, once the battle is re-opened the channel can be joined again

its the same behaviour as any (temporarily) empty registered channel has

**Comment by abma** [comment]
nice!

ok, thanks for explaining!
