### ISSUE TITLE
require tls for battle hosting

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#367]
SPADS now supports TLS in stable, and battle hosts send/recieve data relating to other users

imo it can still be left as optional for players - and also for all once ingame, because of the technical req for low latency - and still be in the spirit of gdpr

@abma ok?

**Comment by abma** [comment]
when ingame no data is sent via uberserver / lobbyclients / spads: spring handles communication itself.

its spads which proxies i.e. messages to and from the lobby.

so TLS required for hosting IMHO is ok.

**Comment by silentwings** [comment]
yes exactly, thought of ingame only for gdpr reasons

**Comment by silentwings** [comment]
https://github.com/spring/uberserver/commit/0ca5b0c9571067c7a19f318b326dcc4c7348c650

**Comment by abma** [comment]
https://github.com/spring/uberserver/commit/339a57bafd79baf31076452eebf1276a17a4700a
