### ISSUE TITLE
allow the same displayname from the same location

### ISSUE THREAD

**Issue by TurBoss** [spring/uberserver#373]
Hello,

I'm having issues to bridge users that have the same displayname and location but diferent userid

"@TurBoss:springrts.com" external_username "TurBoss" external_ID "TurBoss"
"@id_11111:springrts.com" external_username "TurBoss" external_ID "id_11111"

both having the same location
the extrenal_ID is something that will not change but the external_username could

Thanks

**Comment by TurBoss** [comment]
about the db, could the table "bridged_users" be cleaned?

**Comment by silentwings** [comment]
> I'm having issues to bridge users that have the same displayname and location but diferent userid

Error message? How to reproduce?

> about the db, could the table "bridged_users" be cleaned?

Fine by me (I think you have enough access to do it?).

**Comment by TurBoss** [comment]
> > I'm having issues to bridge users that have the same displayname and location but diferent userid
> 
> It's disallowed because all client GUIs assume that usernames (which for bridged users have the form external_username:location) assume that usernames are unique to clients.
> 
> Why would an external location contain two identically named users?!

ok 
> > about the db, could the table "bridged_users" be cleaned?
> 
> Fine by me (I think you have enough access to do it?).
