### ISSUE TITLE
add a method to sync bridged users in one or more chunks

### ISSUE THREAD

**Issue by TurBoss** [spring/uberserver#378]
currently at appservice boot it joins all the bridged rooms and syns one by one all the users

havinf 300 in gamedev takes like 1 or 2 mins to send all of them

and the users can talk meanwhile...

could some bulk sync be added?

**Comment by silentwings** [comment]
It could be added, but the server time involved here is mostly spent telling other clients that the new bridged clients exist, so I'm not sure it would actually help.

What matters is that messages are sent to the server in an order that makes sense e.g. you should send the message saying that a bridge client exists _before_ you send a message in which the client talks. It doesn't matter if they have to sit in a queue for a bit; as long as they are in the right order they will still be dealt with correctly.

**Comment by abma** [comment]
> currently at appservice boot

how often is the appservice restarted?

i guess not this often?!

**Comment by silentwings** [comment]
Outside of testing/developing, I guess not often.

**Comment by abma** [comment]
am i right with it, that the appservice syncs like this:

```
users = getusersfromdiscord()
for user in users:
       uberserver.send(user joined...)
       assert(uberserver.recv() == "joined")
```

shouldn't it be:

```
users = getusersfromdiscord()
uberserver.send("\n".join(users))
...
```

afaik thats supported by uberserver.

**Comment by silentwings** [comment]
Yep, can send multiple commands in a single message, separated by newline chars.

**Comment by TurBoss** [comment]
that great I'll test it

**Comment by TurBoss** [comment]
ok thanks this will do
