### ISSUE TITLE
Wrong client battle status broadcasted when changing bot flag

### ISSUE THREAD

**Issue by Yaribz** [spring/uberserver#383]
When the SETBOTMODE command is used, the status of the client issuing the command is broadcasted instead of the one being modified

https://github.com/spring/uberserver/blob/cc4155c3b45e8189100d9dd9097a9aa04c0eb3ec/protocol/Protocol.py#L2607

**Comment by abma** [comment]
see #379

**Comment by Yaribz** [comment]
duplicate indeed
