### ISSUE TITLE
Help with data migration to new Uberserver instance

### ISSUE THREAD

**Issue by springraaar** [spring/uberserver#398]
I'm considering moving to a new uberserver instance running from my own server for various reasons.

I request a dump of the uberserver's DB on springrts.com (possibly sanitized, we can discuss the details somewhere) so i can preload the set of registered users to avoid having to ask everyone to register again and keep the consistency of player IDs on the MF website.

PS: check your forum PMs Abma, this isn't really an uberserver issue but i have no other way to contact you..

**Comment by abma** [comment]
sorry, i can't really help.

IMHO moving the DB this violates against the https://springrts.com/wiki/Terms_of_Service:

"The SpringRTS server and its managed game hosts process and retain data generated by their users"

In my understanding the "SpringRTS server" is the server hosting springrts.com. You have to ask all users if they confirm the movement to avoid conflicts.

**Comment by springraaar** [comment]
nevermind then, i'll change my infra to use id+server to differentiate between the old and new lobby server users.
