### ISSUE TITLE
renames.new is redundant

### ISSUE THREAD

**Issue by abma** [spring/uberserver#40]
its already stored in users.username

**Comment by silentwings** [comment]
I think renames.new should be kept, it is useful record keeping

**Comment by abma** [comment]
redundant data in a db is always bad as is allows inconsistencies.

why should it be kept, which information isn't there without it the field?

**Comment by silentwings** [comment]
if a user renames twice, without it there would be nothing to connect them to their original username?

**Comment by silentwings** [comment]
oh, ignore me, the user_id is there....

**Comment by abma** [comment]
exactly :-)
