### ISSUE TITLE
add some compatibility code for saybattleprivate crap

### ISSUE THREAD

**Issue by abma** [spring/uberserver#57]
https://github.com/spring/uberserver/commit/70090b47d277b3565303cf4db15ff206927d8b62
https://github.com/spring/uberserver/commit/78883ca132308b4810ca2e4dadca4404184d5f20

-> map to SAYPRIVATE / SAYPRIVATEEX

**Comment by silentwings** [comment]
Afaics, no need anymore & this can be closed.

**Comment by silentwings** [comment]
Does SAYBATTLEPRIVATE actually get used by anything anymore? (It simply routes to SAIDBATTLE now, and afaics has no good reason to exist at all.)

I suggest rename this ticket to "remove SAYBATTLEPRIVATE crap" :p

**Comment by silentwings** [comment]
Removed it as part of #282

**Comment by silentwings** [comment]
Fixed by https://github.com/spring/uberserver/pull/282/commits/1806922df3375f9a31004eda950bc2a4f6ddcf1a

**Comment by silentwings** [comment]
https://github.com/spring/uberserver/pull/282/commits/1806922df3375f9a31004eda950bc2a4f6ddcf1a
