### ISSUE TITLE
HOSTPORT should be sent when a user joins battle after game start

### ISSUE THREAD

**Issue by cleanrock** [spring/uberserver#94]
This is very minor issue, i just wan't to report it while i remember it.
According to specification HOSTPORT is sent just before game start and i see in uberserver code that this is the case in in_MYSTATUS (it is sent when host client switches to ingame).
I think it also should be sent when a player joins after game start and tries to join/rejoin, this can happen for players trying reconnect and spectators.

**Comment by abma** [comment]
fix it by adding it to SETSCRIPTTAGS imo is more reasonable, see #135
